version: '3' 
services:
  backend: 
    container_name: "backend-currency-converter"  
    build:
      context: ./backend  
    ports:
      - 9090:9090
    environment: 
      network_mode: "host"
  frontend: 
    container_name: "frontend-currency-converter"  
    depends_on:  
    - backend
    build:
      context: ./frontend  
    ports:
      - 3001:80
    environment: 
      network_mode: "host" 